default: &default
  adapter: postgresql
  encoding: unicode

  pool: 5

development:
  <<: *default
  database: rails_belt_exam_development


test:
  <<: *default
  database: rails_belt_exam_test


production:
  <<: *default
  database: rails_belt_exam_production
  username: rails_belt_exam
  password: <%= ENV['RAILS_TEMPLATE_LOGIN_REG_DATABASE_PASSWORD'] %>
